version: "3.8"
services:
  backend:
   # image: gahbr/parrot-java:latest
    build: .
    restart: always
    container_name: parrot-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - localstack
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
  localstack:
    image: localstack/localstack
    container_name: localstack_demo
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
      - "8055:8080"
    environment:
      - SERVICES=s3
      - debug=1
      - DATA_DIR=tmp/localstock/data
      - PERSISTANCE=1
    volumes:
      - ~/tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  kafka:
    container_name: my-kafka
    depends_on:
      - zookeeper
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

networks:
  default:
    name: sysmap-network