version: "3.8"
services:
 localstack:
   image: localstack/localstack
   container_name: localstack_demo
   ports:
    - "4566:4566"
    - "4510-4559:4510-4559"
    - "8055:8080"
   environment:
   - SERVICES=s3
   - debug=1
   - DATA_DIR=tmp/localstock/data
   volumes:
   - ./tmp/localstack:/tmp/localstack
   - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: photo-network